### ISSUE TITLE
Decide on Technologies

### ISSUE THREAD

**Issue by Maigard** [flarinerin/conify#15]
As a developer I want to decide on the technologies we should use.

**Comment by tsuckow** [comment]
I presume we need to support ios, Android, windows phone/tablets. Unless we want to do cross device development that probably puts us in HTML5. 

Which probably means react or ember. My recommendation is react.

**Comment by Maigard** [comment]
We were thinking about trying out graphql as opposed to a rest interface with ruby on rails on the backend. Something like https://github.com/calebmer/postgraphql . We are going to evaluate it and report back next week.

As far as the front end, it would definitely be an HTML interface. We were talking about ember, but this might be a good project to do some playing around with react. We will have to talk about that next week as well.

**Comment by flarinerin** [comment]
http://v4-alpha.getbootstrap.com/
Not quite ready for prime time yet, but would probably be fun to play with and work good 'nuff.
I'm guessing that with bootstrap we'll all move quicker due to familiarity, and with 5-ish weeks to develop and introduce new tech elseware in the app, it might be best to go with what we know.

http://foundation.zurb.com/apps.html
I've used zurb stuff before and it's pretty good, takes a bit more tweaking to get styles more prettier but doesn't mess with containers for a cleaner DOM. Zurb Foundation for apps uses Angular though.
http://foundation.zurb.com/apps/page-templates.html Some great out of the box templates that kind of resemble some sketches we've done already. May be an easy solution with this new toy.

https://github.com/zurb/foundation-apps/wiki/Contributing someone is working on porting it to React

**Comment by Samsinite** [comment]
I would personally love to use react in this project. I use ember pretty much every day, and it would be nice to play with something different.

**Comment by Samsinite** [comment]
What about couchdb/pouchdb react, redux, and webpack?

**Comment by chadzink** [comment]
Rails backend with Postgres
React front end with bootstrap-4
